export const countries = [
  {
    code: 'AF',
    en: `Afghanistan`,
    mn: 'Афганистан',
    id: 'Afganistan',
  },
  {
    code: 'AL',
    en: `Albania`,
    mn: 'Албани улс',
    id: 'Albania',
  },
  {
    code: 'DZ',
    en: `Algeria`,
    mn: 'Алжир',
    id: 'Aljazair',
  },
  {
    code: 'AS',
    en: `American Samoa`,
    mn: 'Америкийн Самоа',
    id: 'Samoa Amerika',
  },
  {
    code: 'AD',
    en: `Andorra`,
    mn: 'Андорра',
    id: 'Andorra',
  },
  {
    code: 'AO',
    en: `Angola`,
    mn: 'Ангол улс',
    id: 'Angola',
  },
  {
    code: 'AI',
    en: `Anguilla`,
    mn: 'Ангилл',
    id: 'Anguilla',
  },
  {
    code: 'AQ',
    en: `Antarctica`,
    mn: 'Антарктид',
    id: 'Antartika',
  },
  {
    code: 'AG',
    en: `Antigua and Barbuda`,
    mn: 'Антигуа ба Барбуда',
    id: 'Antigua dan Barbuda',
  },
  {
    code: 'AR',
    en: `Argentina`,
    mn: 'Аргентин',
    id: 'Argentina',
  },
  {
    code: 'AM',
    en: `Armenia`,
    mn: 'Армени',
    id: 'Armenia',
  },
  {
    code: 'AW',
    en: `Aruba`,
    mn: 'Аруба',
    id: 'Aruba',
  },
  {
    code: 'AU',
    en: `Australia`,
    mn: 'Австрали',
    id: 'Australia',
  },
  {
    code: 'AT',
    en: `Austria`,
    mn: 'Австри',
    id: 'Austria',
  },
  {
    code: 'AZ',
    en: `Azerbaijan`,
    mn: 'Азербайжан улс',
    id: 'Azerbaijan',
  },
  {
    code: 'BS',
    en: `Bahamas`,
    mn: 'Багамын арлууд',
    id: 'Bahama',
  },
  {
    code: 'BH',
    en: `Bahrain`,
    mn: 'Багамын арлууд',
    id: 'Bahama',
  },
  {
    code: 'BD',
    en: `Bangladesh`,
    mn: 'Бангладеш',
    id: 'Bangladesh',
  },
  {
    code: 'BB',
    en: `Barbados`,
    mn: 'Барбадос',
    id: 'Barbados',
  },
  {
    code: 'BY',
    en: `Belarus`,
    mn: 'Беларусь улс',
    id: 'Belarus',
  },
  {
    code: 'BE',
    en: `Belgium`,
    mn: 'Бельги улс',
    id: 'Belgium',
  },
  {
    code: 'BZ',
    en: `Belize`,
    mn: 'Белиз',
    id: 'Belize',
  },
  {
    code: 'BJ',
    en: `Benin`,
    mn: 'Бенин',
    id: 'Benin',
  },
  {
    code: 'BM',
    en: `Bermuda`,
    mn: 'Бермудын',
    id: 'Bermuda',
  },
  {
    code: 'BT',
    en: `Bhutan`,
    mn: 'Бутан',
    id: 'Bhutan',
  },
  {
    code: 'BO',
    en: `Bolivia `,
    mn: 'Боливи',
    id: 'Bolivia',
  },
  {
    code: 'BQ',
    en: `Bonaire`,
    mn: 'Бонайре',
    id: 'Bonaire',
  },
  {
    code: 'BA',
    en: `Bosnia and Herzegovina`,
    mn: 'Босни ба Херцеговина',
    id: 'Bosnia dan Herzegovina',
  },
  {
    code: 'BW',
    en: `Botswana`,
    mn: 'Ботсвана улс',
    id: 'Botswana',
  },
  {
    code: 'BV',
    en: `Bouvet Island`,
    mn: 'Bouvet Island',
    id: 'Pulau Bouvet',
  },
  {
    code: 'BR',
    en: `Brazil`,
    mn: 'Бразил',
    id: 'Brazil',
  },
  {
    code: 'IO',
    en: `British Indian Ocean Ter`,
    mn: 'Британийн Энэтхэгийн далайн нутаг',
    id: 'Wilayah Samudra Hindia Britania',
  },
  {
    code: 'VG',
    en: `British Virgin Islands`,
    mn: 'Британийн Виржиний арлууд',
    id: 'Kepulauan Virgin Inggris',
  },
  {
    code: 'BN',
    en: `Brunei Darussalam`,
    mn: 'Бруней',
    id: 'Brunei',
  },
  {
    code: 'BG',
    en: `Bulgaria`,
    mn: 'Болгар',
    id: 'Bulgaria',
  },
  {
    code: 'BF',
    en: `Burkina Faso`,
    mn: 'Буркина Фасо',
    id: 'Burkina Faso',
  },
  {
    code: 'BI',
    en: `Burundi`,
    mn: 'Бурунди улс',
    id: 'Burundi',
  },
  {
    code: 'KH',
    en: `Cambodia`,
    mn: 'Камбож',
    id: 'Kamboja',
  },
  {
    code: 'CM',
    en: `Cameroon`,
    mn: 'Камерун',
    id: 'Kamerun',
  },
  {
    code: 'CA',
    en: `Canada`,
    mn: 'Канад',
    id: 'Kanada',
  },
  {
    code: 'CV',
    en: `Cape Verde`,
    mn: 'Кабо Верде',
    id: 'Tanjung Verde',
  },
  {
    code: 'KY',
    en: `Cayman Islands`,
    mn: 'Кайманы арлууд',
    id: 'Pulau cayman',
  },
  {
    code: 'CF',
    en: `Central African Republic`,
    mn: 'Төв Африкийн бүгд найрамдах улс',
    id: 'Republik Afrika Tengah',
  },
  {
    code: 'TD',
    en: `Chad`,
    mn: 'Чад улс',
    id: 'Chad',
  },
  {
    code: 'CL',
    en: `Chile`,
    mn: 'Чили',
    id: 'Chili',
  },
  {
    code: 'CN',
    en: `China`,
    mn: 'Хятад улс',
    id: 'Cina',
  },
  {
    code: 'CX',
    en: `Christmas Island`,
    mn: 'Зул сарын арал',
    id: 'Pulau Natal',
  },
  {
    code: 'CC',
    en: `Cocos [Keeling] Islands`,
    mn: 'Кокос [Килинг] Арлууд',
    id: 'Kepulauan Cocos [Keeling]',
  },
  {
    code: 'CO',
    en: `Colombia`,
    mn: 'Колумб',
    id: 'Kolumbia',
  },
  {
    code: 'KM',
    en: `Comoros`,
    mn: 'Комор улс',
    id: 'Komoro',
  },
  {
    code: 'CK',
    en: `Cook Islands`,
    mn: 'Күүкийн арлууд',
    id: 'Kepulauan Cook',
  },
  {
    code: 'CR',
    en: `Costa Rica`,
    mn: 'Коста Рика',
    id: 'Kosta Rika',
  },
  {
    code: 'HR',
    en: `Croatia`,
    mn: 'Хорват улс',
    id: 'Kroasia',
  },
  {
    code: 'CU',
    en: `Cuba`,
    mn: 'Куба улс',
    id: 'Kuba',
  },
  {
    code: 'CW',
    en: `Curacao`,
    mn: 'Кюрасао',
    id: 'Curacao',
  },
  {
    code: 'CY',
    en: `Cyprus`,
    mn: 'Кипр',
    id: 'Siprus',
  },
  {
    code: 'CZ',
    en: `Czech Republic`,
    mn: 'Чех улс',
    id: 'Republik Ceko',
  },
  {
    code: 'CD',
    en: `Democratic Republic of Congo`,
    mn: 'Бүгд Найрамдах Ардчилсан Конго улс',
    id: 'Republik Demokrasi Kongo',
  },
  {
    code: 'DK',
    en: `Denmark`,
    mn: 'Дани улс',
    id: 'Denmark',
  },
  {
    code: 'DJ',
    en: `Djibouti`,
    mn: 'Жибути',
    id: 'Djibouti',
  },
  {
    code: 'DM',
    en: `Dominica`,
    mn: 'Доминика',
    id: 'Dominica',
  },
  {
    code: 'DO',
    en: `Dominican Republic`,
    mn: 'Доминиканы бүгд найрамдах улс',
    id: 'Republik Dominika',
  },
  {
    code: 'TL',
    en: `Timor-Leste`,
    mn: 'Зүүн Тимор',
    id: 'Timor Timur',
  },
  {
    code: 'EC',
    en: `Ecuador`,
    mn: 'Эквадор улс',
    id: 'Ekuador',
  },
  {
    code: 'EG',
    en: `Egypt`,
    mn: 'Египет',
    id: 'Mesir',
  },
  {
    code: 'SV',
    en: `El Salvador`,
    mn: 'Сальвадор улс',
    id: 'El Salvador',
  },
  {
    code: 'GQ',
    en: `Equatorial Guinea`,
    mn: 'Экваторын Гвиней',
    id: 'Guinea ekuator',
  },
  {
    code: 'ER',
    en: `Eritrea`,
    mn: 'Эритрей',
    id: 'Eritrea',
  },
  {
    code: 'EE',
    en: `Estonia`,
    mn: 'Эстон',
    id: 'Estonia',
  },
  {
    code: 'ET',
    en: `Ethiopia`,
    mn: 'Этиоп улс',
    id: 'Etiopia',
  },
  {
    code: 'FK',
    en: `Falkland Islands`,
    mn: 'Фолкландын арлууд',
    id: 'Kepulauan Falkland',
  },
  {
    code: 'FO',
    en: `Faroe Islands`,
    mn: 'Фарерын арлууд',
    id: 'Kepulauan Faroe',
  },
  {
    code: 'FJ',
    en: `Fiji`,
    mn: 'Фижи улс',
    id: 'Fiji',
  },
  {
    code: 'FI',
    en: `Finland`,
    mn: 'Финлянд',
    id: 'Finlandia',
  },
  {
    code: 'FR',
    en: `France`,
    mn: 'Франц',
    id: 'Perancis',
  },
  {
    code: 'GF',
    en: `French Guiana`,
    mn: 'Францын Гвиана',
    id: 'Guyana Perancis',
  },
  {
    code: 'PF',
    en: `French Polynesia`,
    mn: 'Францын Полинези',
    id: 'Polinesia Perancis',
  },
  {
    code: 'TF',
    en: `French Southern Territor`,
    mn: 'Францын өмнөд нутаг',
    id: 'Wilayah Selatan Prancis',
  },
  {
    code: 'GA',
    en: `Gabon`,
    mn: 'Габон',
    id: 'Gabon',
  },
  {
    code: 'GM',
    en: `Gambia`,
    mn: 'Гамби',
    id: 'Gambia',
  },
  {
    code: 'GE',
    en: `Georgia`,
    mn: 'Гүрж',
    id: 'Georgia',
  },
  {
    code: 'DE',
    en: `Germany`,
    mn: 'Герман',
    id: 'Jerman',
  },
  {
    code: 'GH',
    en: `Ghana`,
    mn: 'Гана улс',
    id: 'Ghana',
  },
  {
    code: 'GI',
    en: `Gibraltar`,
    mn: 'Гибралтар',
    id: 'Gibraltar',
  },
  {
    code: 'GR',
    en: `Greece`,
    mn: 'Грек улс',
    id: 'Yunani',
  },
  {
    code: 'GL',
    en: `Greenland`,
    mn: 'Гренланд',
    id: 'Tanah penggembalaan',
  },
  {
    code: 'GD',
    en: `Grenada`,
    mn: 'Гренада',
    id: 'Grenada',
  },
  {
    code: 'GP',
    en: `Guadeloupe`,
    mn: 'Гваделупа',
    id: 'Guadeloupe',
  },
  {
    code: 'GU',
    en: `Guam`,
    mn: 'Гуам',
    id: 'Guam',
  },
  {
    code: 'GT',
    en: `Guatemala`,
    mn: 'Гватемал',
    id: 'Guatemala',
  },
  {
    code: 'GG',
    en: `Guernsey`,
    mn: 'Гернси',
    id: 'Guernsey',
  },
  {
    code: 'GN',
    en: `Guinea`,
    mn: 'Гвиней',
    id: 'Guinea',
  },
  {
    code: 'GW',
    en: `Guinea-Bissau`,
    mn: 'Гвиней-Бисау',
    id: 'Guinea-Bissau',
  },
  {
    code: 'GY',
    en: `Guyana`,
    mn: 'Гайана',
    id: 'Guyana',
  },
  {
    code: 'HT',
    en: `Haiti`,
    mn: 'Гайти улс',
    id: 'Haiti',
  },
  {
    code: 'HM',
    en: `Heard Island and McDonal`,
    mn: 'Херд ба Макдоналд арлууд',
    id: 'Pulau Heard dan Kepulauan McDonald',
  },
  {
    code: 'HN',
    en: `Honduras`,
    mn: 'Гондурас',
    id: 'Honduras',
  },
  {
    code: 'HK',
    en: `Hong Kong`,
    mn: 'Хонг Конг',
    id: 'Hongkong',
  },
  {
    code: 'HU',
    en: `Hungary`,
    mn: 'Унгар',
    id: 'Hungaria',
  },
  {
    code: 'IS',
    en: `Iceland`,
    mn: 'Исланд улс',
    id: 'Islandia',
  },
  {
    code: 'IN',
    en: `India`,
    mn: 'Энэтхэг',
    id: 'India',
  },
  {
    code: 'ID',
    en: `Indonesia`,
    mn: 'Индонез',
    id: 'Indonesia',
  },
  {
    code: 'IR',
    en: `Iran`,
    mn: 'Иран',
    id: 'Iran',
  },
  {
    code: 'IQ',
    en: `Iraq`,
    mn: 'Ирак',
    id: 'Irak',
  },
  {
    code: 'IE',
    en: `Ireland`,
    mn: 'Ирланд',
    id: 'Irlandia',
  },
  {
    code: 'IM',
    en: `Isle of Man`,
    mn: 'Хүний арал',
    id: 'Pulau manusia',
  },
  {
    code: 'IL',
    en: `Israel`,
    mn: 'Израиль улс',
    id: 'Israel',
  },
  {
    code: 'IT',
    en: `Italy`,
    mn: 'Итали',
    id: 'Italia',
  },
  {
    code: 'CI',
    en: `Ivory Coast`,
    mn: 'Зааны Ясан эрэг',
    id: 'pantai Gading',
  },
  {
    code: 'JM',
    en: `Jamaica`,
    mn: 'Ямайка',
    id: 'Jamaika',
  },
  {
    code: 'JP',
    en: `Japan`,
    mn: 'Япон',
    id: 'Jepang',
  },
  {
    code: 'JE',
    en: `Jersey`,
    mn: 'Жерси',
    id: 'Jersey',
  },
  {
    code: 'JO',
    en: `Jordan`,
    mn: 'Жордан',
    id: 'Yordania',
  },
  {
    code: 'KZ',
    en: `Kazakhstan`,
    mn: 'Казахстан улс',
    id: 'Kazakhstan',
  },
  {
    code: 'KE',
    en: `Kenya`,
    mn: 'Кени улс',
    id: 'Kenya',
  },
  {
    code: 'KI',
    en: `Kiribati`,
    mn: 'Кирибати улс',
    id: 'Kiribati',
  },
  {
    code: 'XK',
    en: `Kosovo`,
    mn: 'Косово',
    id: 'Kosovo',
  },
  {
    code: 'KW',
    en: `Kuwait`,
    mn: 'Кувейт улс',
    id: 'Kuwait',
  },
  {
    code: 'KG',
    en: `Kyrgyzstan`,
    mn: 'Киргизстан',
    id: 'Kirgistan',
  },
  {
    code: 'LA',
    en: `Laos`,
    mn: 'Лаос улс',
    id: 'Laos',
  },
  {
    code: 'LV',
    en: `Latvia`,
    mn: 'Латви улс',
    id: 'Latvia',
  },
  {
    code: 'LB',
    en: `Lebanon`,
    mn: 'Ливан',
    id: 'Libanon',
  },
  {
    code: 'LS',
    en: `Lesotho`,
    mn: 'Лесото улс',
    id: 'Lesotho',
  },
  {
    code: 'LR',
    en: `Liberia`,
    mn: 'Либери улс',
    id: 'Liberia',
  },
  {
    code: 'LY',
    en: `Libya`,
    mn: 'Либери улс',
    id: 'Libya',
  },
  {
    code: 'LI',
    en: `Liechtenstein`,
    mn: 'Лихтенштейн',
    id: 'Liechtenstein',
  },
  {
    code: 'LT',
    en: `Lithuania`,
    mn: 'Литва улс',
    id: 'Lithuania',
  },
  {
    code: 'LU',
    en: `Luxembourg`,
    mn: 'Люксембург',
    id: 'Luksemburg',
  },
  {
    code: 'MO',
    en: `Macao`,
    mn: 'Макао улс',
    id: 'Makau',
  },
  {
    code: 'MG',
    en: `Madagascar`,
    mn: 'Мадагаскар',
    id: 'Madagaskar',
  },
  {
    code: 'MW',
    en: `Malawi`,
    mn: 'Малави',
    id: 'Malawi',
  },
  {
    code: 'MY',
    en: `Malaysia`,
    mn: 'Малайз',
    id: 'Malaysia',
  },
  {
    code: 'MV',
    en: `Maldives`,
    mn: 'Мальдив улсууд',
    id: 'Maladewa',
  },
  {
    code: 'ML',
    en: `Mali`,
    mn: 'Мали улс',
    id: 'Mali',
  },
  {
    code: 'MT',
    en: `Malta`,
    mn: 'Мальта',
    id: 'Malta',
  },
  {
    code: 'MH',
    en: `Marshall Islands`,
    mn: 'Маршалын Арлууд',
    id: 'Pulau Marshall',
  },
  {
    code: 'MQ',
    en: `Martinique`,
    mn: 'Мартиник',
    id: 'Martinique',
  },
  {
    code: 'MR',
    en: `Mauritania`,
    mn: 'Мавритан улс',
    id: 'Mauritania',
  },
  {
    code: 'MU',
    en: `Mauritius`,
    mn: 'Мавритани',
    id: 'Mauritius',
  },
  {
    code: 'YT',
    en: `Mayotte`,
    mn: 'Майотте',
    id: 'Mayotte',
  },
  {
    code: 'MX',
    en: `Mexico`,
    mn: 'Мексик',
    id: 'Meksiko',
  },
  {
    code: 'FM',
    en: `Micronesia`,
    mn: 'Микронезийн',
    id: 'Mikronesia',
  },
  {
    code: 'MD',
    en: `Moldova`,
    mn: 'Молдав',
    id: 'Moldova',
  },
  {
    code: 'MC',
    en: `Monaco`,
    mn: 'Монако',
    id: 'Monako',
  },
  {
    code: 'MN',
    en: `Mongolia`,
    mn: 'Монгол',
    id: 'Mongolia',
  },
  {
    code: 'ME',
    en: `Montenegro`,
    mn: 'Монтенегро',
    id: 'Montenegro',
  },
  {
    code: 'MS',
    en: `Montserrat`,
    mn: 'Монцеррат',
    id: 'Montserrat',
  },
  {
    code: 'MA',
    en: `Morocco`,
    mn: 'Марокко',
    id: 'Maroko',
  },
  {
    code: 'MZ',
    en: `Mozambique`,
    mn: 'Мозамбик',
    id: 'Mozambik',
  },
  {
    code: 'MM',
    en: `Myanmar [Burma]`,
    mn: 'Мьянмар [Бирма]',
    id: 'Myanmar [Burma]',
  },
  {
    code: 'NA',
    en: `Namibia`,
    mn: 'Намиби улс',
    id: 'Namibia',
  },
  {
    code: 'NR',
    en: `Nauru`,
    mn: 'Науру',
    id: 'Nauru',
  },
  {
    code: 'NP',
    en: `Nepal`,
    mn: 'Балба',
    id: 'Nepal',
  },
  {
    code: 'NL',
    en: `Netherlands`,
    mn: 'Нидерланд',
    id: 'Belanda',
  },
  {
    code: 'NC',
    en: `New Caledonia`,
    mn: 'Шинэ Каледони',
    id: 'Kaledonia Baru',
  },
  {
    code: 'NZ',
    en: `New Zealand`,
    mn: 'Шинэ Зеланд',
    id: 'Selandia Baru',
  },
  {
    code: 'NI',
    en: `Nicaragua`,
    mn: 'Никарагуа',
    id: 'Nikaragua',
  },
  {
    code: 'NE',
    en: `Niger`,
    mn: 'Нигер улс',
    id: 'Niger',
  },
  {
    code: 'NG',
    en: `Nigeria`,
    mn: 'Нигери',
    id: 'Nigeria',
  },
  {
    code: 'NU',
    en: `Niue`,
    mn: 'Ниуэ',
    id: 'Niue',
  },
  {
    code: 'NF',
    en: `Norfolk Island`,
    mn: 'Норфолкийн арал',
    id: 'Pulau Norfolk',
  },
  {
    code: 'KP',
    en: `North Korea`,
    mn: 'Хойд Солонгос',
    id: 'Korea Utara',
  },
  {
    code: 'MK',
    en: `North Macedonia`,
    mn: 'Хойд Македони',
    id: 'Makedonia Utara',
  },
  {
    code: 'MP',
    en: `Northern Mariana Islands`,
    mn: 'Марианийн хойд арлууд',
    id: 'Kepulauan Mariana Utara',
  },
  {
    code: 'NO',
    en: `Norway`,
    mn: 'Норвеги улс',
    id: 'Norway',
  },
  {
    code: 'OM',
    en: `Oman`,
    mn: 'Оман улс',
    id: 'Oman',
  },
  {
    code: 'PK',
    en: `Pakistan`,
    mn: 'Пакистан',
    id: 'Pakistan',
  },
  {
    code: 'PW',
    en: `Palau`,
    mn: 'Палау',
    id: 'Palau',
  },
  {
    code: 'PS',
    en: `State of Palestine`,
    mn: 'Палестин',
    id: 'Palestina',
  },
  {
    code: 'PA',
    en: `Panama`,
    mn: 'Панамын',
    id: 'Panama',
  },
  {
    code: 'PG',
    en: `Papua New Guinea`,
    mn: 'Папуа Шинэ Гвиней',
    id: 'Papua Nugini',
  },
  {
    code: 'PY',
    en: `Paraguay`,
    mn: 'Парагвай',
    id: 'Paraguay',
  },
  {
    code: 'PE',
    en: `Peru`,
    mn: 'Перу улс',
    id: 'Peru',
  },
  {
    code: 'PH',
    en: `Philippines`,
    mn: 'Филиппин',
    id: 'Filipina',
  },
  {
    code: 'PN',
    en: `Pitcairn Islands`,
    mn: 'Питкэрн арлууд',
    id: 'Kepulauan Pitcairn',
  },
  {
    code: 'PL',
    en: `Poland`,
    mn: 'Польш улс',
    id: 'Polandia',
  },
  {
    code: 'PT',
    en: `Portugal`,
    mn: 'Португал',
    id: 'Portugal',
  },
  {
    code: 'PR',
    en: `Puerto Rico`,
    mn: 'Пуэрто-Рико',
    id: 'Puerto Riko',
  },
  {
    code: 'QA',
    en: `Qatar`,
    mn: 'Катар',
    id: 'Qatar',
  },
  {
    code: 'CG',
    en: `Republic of the Congo`,
    mn: 'Бүгд Найрамдах Конго улс',
    id: 'Republik Kongo',
  },
  {
    code: 'RO',
    en: `Romania`,
    mn: 'Румын улс',
    id: 'Rumania',
  },
  {
    code: 'RU',
    en: `Russia`,
    mn: 'Орос',
    id: 'Rusia',
  },
  {
    code: 'RW',
    en: `Rwanda`,
    mn: 'Руанда улс',
    id: 'Rwanda',
  },
  {
    code: 'RE',
    en: `Réunion`,
    mn: 'Рэунион',
    id: 'Reuni',
  },
  {
    code: 'BL',
    en: `Saint Barthélemy`,
    mn: 'Гэгээн Бартелеми',
    id: 'Saint Barthelemy',
  },
  {
    code: 'SH',
    en: `Saint Helena`,
    mn: 'Гэгээн Елена',
    id: 'Saint Helena',
  },
  {
    code: 'KN',
    en: `Saint Kitts and Nevis`,
    mn: 'Сент Киттс ба Невис',
    id: 'Saint Kitts dan Nevis',
  },
  {
    code: 'LC',
    en: `Saint Lucia`,
    mn: 'Сент Люсиа',
    id: 'Saint Lucia',
  },
  {
    code: 'MF',
    en: `Saint Martin`,
    mn: 'Гэгээн Мартин',
    id: 'Saint Martin',
  },
  {
    code: 'PM',
    en: `Saint Pierre and Miquelo`,
    mn: 'Сент Пьер ба Микелон',
    id: 'Saint Pierre dan Miquelon',
  },
  {
    code: 'VC',
    en: `Saint Vincent and the Gr`,
    mn: 'Сент-Винсент ба Гренадин',
    id: 'Saint Vincent dan Grenadines',
  },
  {
    code: 'WS',
    en: `Samoa`,
    mn: 'Самоа',
    id: 'Samoa',
  },
  {
    code: 'SM',
    en: `San Marino`,
    mn: 'Сан Марино',
    id: 'San Marino',
  },
  {
    code: 'SA',
    en: `Saudi Arabia`,
    mn: 'Саудын Араб',
    id: 'Arab Saudi',
  },
  {
    code: 'SN',
    en: `Senegal`,
    mn: 'Сенегал улс',
    id: 'Senegal',
  },
  {
    code: 'RS',
    en: `Serbia`,
    mn: 'Серби',
    id: 'Serbia',
  },
  {
    code: 'SC',
    en: `Seychelles`,
    mn: 'Сейшелийн арлууд',
    id: 'Seychelles',
  },
  {
    code: 'SL',
    en: `Sierra Leone`,
    mn: 'Сьерра-Леон',
    id: 'Sierra Leone',
  },
  {
    code: 'SG',
    en: `Singapore`,
    mn: 'Сингапур',
    id: 'Singapura',
  },
  {
    code: 'SX',
    en: `Sint Maarten`,
    mn: 'Синт Мартен',
    id: 'Sint Maarten',
  },
  {
    code: 'SK',
    en: `Slovakia`,
    mn: 'Словак улс',
    id: 'Slovakia',
  },
  {
    code: 'SI',
    en: `Slovenia`,
    mn: 'Словени улс',
    id: 'Slovenia',
  },
  {
    code: 'SB',
    en: `Solomon Islands`,
    mn: 'Соломоны арлууд',
    id: 'Pulau Solomon',
  },
  {
    code: 'SO',
    en: `Somalia`,
    mn: 'Сомали',
    id: 'Somalia',
  },
  {
    code: 'ZA',
    en: `South Africa`,
    mn: 'Өмнөд Африк',
    id: 'Afrika Selatan',
  },
  {
    code: 'KR',
    en: `South Korea`,
    mn: 'Өмнөд Солонгос',
    id: 'Korea Selatan',
  },
  {
    code: 'SS',
    en: `South Sudan`,
    mn: 'Өмнөд Судан',
    id: 'Sudan Selatan',
  },
  {
    code: 'ES',
    en: `Spain`,
    mn: 'Испани улс',
    id: 'Spanyol',
  },
  {
    code: 'LK',
    en: `Sri Lanka`,
    mn: 'Шри Ланка',
    id: 'Srilanka',
  },
  {
    code: 'SD',
    en: `Sudan`,
    mn: 'Судан улс',
    id: 'Sudan',
  },
  {
    code: 'SR',
    en: `Suriname`,
    mn: 'Суринам',
    id: 'Suriname',
  },
  {
    code: 'SJ',
    en: `Svalbard and Jan Mayen`,
    mn: 'Шпицберд ба Ян Майен нар',
    id: 'Svalbard dan Jan Mayen',
  },
  {
    code: 'SZ',
    en: `Swaziland`,
    mn: 'Свазиленд улс',
    id: 'Swaziland',
  },
  {
    code: 'SE',
    en: `Sweden`,
    mn: 'Швед',
    id: 'Swedia',
  },
  {
    code: 'CH',
    en: `Switzerland`,
    mn: 'Швейцарь',
    id: 'Swiss',
  },
  {
    code: 'SY',
    en: `Syrian Arab Republic`,
    mn: 'Сири улс',
    id: 'Syria',
  },
  {
    code: 'ST',
    en: `São Tomé and Príncipe`,
    mn: 'Сан Томе, Принцип',
    id: 'São Tomé dan Príncipe',
  },
  {
    code: 'TW',
    en: `Taiwan`,
    mn: 'Тайвань',
    id: 'Taiwan',
  },
  {
    code: 'TJ',
    en: `Tajikistan`,
    mn: 'Тажикстан',
    id: 'Tajikistan',
  },
  {
    code: 'TZ',
    en: `Tanzania`,
    mn: 'Танзани улс',
    id: 'Tanzania',
  },
  {
    code: 'TH',
    en: `Thailand`,
    mn: 'Тайланд улс',
    id: 'Thailand',
  },
  {
    code: 'TG',
    en: `Togo`,
    mn: 'Явах',
    id: 'Untuk pergi',
  },
  {
    code: 'TK',
    en: `Tokelau`,
    mn: 'Токелау',
    id: 'Tokelau',
  },
  {
    code: 'TO',
    en: `Tonga`,
    mn: 'Тонга',
    id: 'Tonga',
  },
  {
    code: 'TT',
    en: `Trinidad and Tobago`,
    mn: 'Тринидад Тобаго',
    id: 'Trinidad dan Tobago',
  },
  {
    code: 'TN',
    en: `Tunisia`,
    mn: 'Тунис',
    id: 'Tunisia',
  },
  {
    code: 'TR',
    en: `Turkey`,
    mn: 'Турк',
    id: 'Turki',
  },
  {
    code: 'TM',
    en: `Turkmenistan`,
    mn: 'Туркменистан',
    id: 'Turkmenistan',
  },
  {
    code: 'TC',
    en: `Turks and Caicos Islands`,
    mn: 'Туркс ба Кайкосын арлууд',
    id: 'Kepulauan Turks dan Caicos',
  },
  {
    code: 'TV',
    en: `Tuvalu`,
    mn: 'Тувалу улс',
    id: 'Tuvalu',
  },
  {
    code: 'UM',
    en: `U.S. Minor Outlying Isla`,
    mn: 'АНУ-ын жижиг жижиг арлууд',
    id: 'Kepulauan Terluar Kecil A.S.',
  },
  {
    code: 'VI',
    en: `U.S. Virgin Islands`,
    mn: 'АНУ-ын Виржиний Арлууд',
    id: 'Kepulauan Virgin A.S.',
  },
  {
    code: 'UG',
    en: `Uganda`,
    mn: 'Уганда',
    id: 'Uganda',
  },
  {
    code: 'UA',
    en: `Ukraine`,
    mn: 'Украйн',
    id: 'Ukraina',
  },
  {
    code: 'AE',
    en: `United Arab Emirates`,
    mn: 'Арабын нэгдсэн Эмират улс',
    id: 'Uni Emirat Arab',
  },
  {
    code: 'GB',
    en: `United Kingdom`,
    mn: 'Нэгдсэн Вант Улс',
    id: 'Britania Raya',
  },
  {
    code: 'US',
    en: `United States of America`,
    mn: 'Нэгдсэн Улс',
    id: 'Amerika Serikat',
  },
  {
    code: 'UY',
    en: `Uruguay`,
    mn: 'Уругвай',
    id: 'Uruguay',
  },
  {
    code: 'UZ',
    en: `Uzbekistan`,
    mn: 'Узбекистан',
    id: 'Uzbekistan',
  },
  {
    code: 'VU',
    en: `Vanuatu`,
    mn: 'Вануату',
    id: 'Vanuatu',
  },
  {
    code: 'VA',
    en: `Vatican City`,
    mn: 'Ватикан хот',
    id: 'Kota Vatikan',
  },
  {
    code: 'VE',
    en: `Venezuela`,
    mn: 'Венесуэл улс',
    id: 'Venezuela',
  },
  {
    code: 'VN',
    en: `Vietnam`,
    mn: 'Вьетнам',
    id: 'Vietnam',
  },
  {
    code: 'WF',
    en: `Wallis and Futuna`,
    mn: 'Уоллис ба Футуна',
    id: 'Wallis dan Futuna',
  },
  {
    code: 'EH',
    en: `Western Sahara`,
    mn: 'Баруун Сахара',
    id: 'Sahara Barat',
  },
  {
    code: 'YE',
    en: `Yemen`,
    mn: 'Йемен улс',
    id: 'Yaman',
  },
  {
    code: 'ZM',
    en: `Zambia`,
    mn: 'Замби улс',
    id: 'Zambia',
  },
  {
    code: 'ZW',
    en: `Zimbabwe`,
    mn: 'Зимбабве',
    id: 'Zimbabwe',
  },
  {
    code: 'AX',
    en: `Åland`,
    mn: 'Аланд',
    id: 'Sebuah daratan',
  },
]
