import { translate } from '../i18n'

export const mainScreenSpeech = ({ todayInfo }) => [
  translate('calendar'),
  todayInfo.cycleLength + translate('days'),
  todayInfo.onPeriod
    ? todayInfo.daysLeftOnPeriod.toString() + translate('left')
    : todayInfo.daysUntilNextPeriod.toString() + translate('to_go'),
  todayInfo.date.format('DD MMMM'),
  translate('day') + todayInfo.cycleDay.toString(),
  translate('mood'),
  translate('body'),
  translate('activity'),
  translate('flow'),
]

export const profileScreenSpeech = ({ currentUser, todayInfo, dateOfBirth }) => [
  translate('profile'),
  translate('name'),
  currentUser.name,
  translate('age'),
  translate(dateOfBirth.format('MMM')) + ' ' + dateOfBirth.format('YYYY'),
  translate('gender'),
  translate(currentUser.gender),
  translate('location'),
  translate(currentUser.location),
  translate('cycle_length'),
  todayInfo.cycleLength.toString() + translate('days'),
  translate('period_length'),
  todayInfo.periodLength.toString() + translate('days'),
]

export const settingsScreenText = () => [
  translate('settings'),
  translate('about'),
  translate('about_info'),
  translate('t_and_c'),
  translate('t_and_c_info'),
  translate('privacy_policy'),
  translate('privacy_info'),
  translate('access_setting'),
  translate('settings_info'),
  translate('text_to_speech'),
  translate('text_to_speech_info'),
  translate('password_request'),
  translate('password_request_info'),
  translate('logout'),
  translate('delete_account_button'),
  translate('contact_us'),
]

export const aboutScreenText = () => [
  translate('about'),
  translate('about_content_1'),
  translate('about_heading_1'),
  translate('about_content_2'),
  translate('about_heading_2'),
  translate('about_content_3'),
  translate('about_content_4'),
  translate('about_content_5'),
  translate('about_heading_3'),
  translate('about_content_6'),
  translate('about_heading_4'),
  translate('about_content_7'),
  translate('about_heading_5'),
  translate('about_content_8'),
  translate('about_content_9'),
]

export const privacyScreenText = () => [
  translate('privacy_heading_1'),
  translate('privacy_content_1'),
  translate('privacy_heading_2'),
  translate('privacy_content_2'),
  translate('privacy_heading_3'),
  translate('privacy_heading_4'),
  translate('privacy_content_3'),
  translate('privacy_heading_5'),
  translate('privacy_content_4'),
  translate('privacy_content_5'),
  translate('privacy_content_6'),
  translate('privacy_content_7'),
  translate('privacy_content_8'),
  translate('privacy_content_9'),
  translate('privacy_content_10'),
  translate('privacy_heading_6'),
  translate('privacy_content_11'),
  translate('privacy_content_12'),
  translate('privacy_content_13'),
  translate('privacy_heading_7'),
  translate('privacy_content_14'),
  translate('privacy_content_15'),
  translate('privacy_heading_8'),
  translate('privacy_content_16'),
  translate('privacy_content_17'),
  translate('privacy_content_18'),
  translate('privacy_heading_9'),
  translate('privacy_content_19'),
  translate('privacy_content_20'),
  translate('privacy_content_21'),
  translate('privacy_heading_10'),
  translate('privacy_content_22'),
  translate('privacy_heading_11'),
  translate('privacy_content_23'),
  translate('privacy_content_24'),
  translate('privacy_content_25'),
  translate('privacy_content_26'),
  translate('privacy_heading_12'),
  translate('privacy_content_27'),
  translate('privacy_heading_13'),
  translate('privacy_content_28'),
  translate('privacy_content_29'),
]

export const termsScreenText = () => [
  translate('terms'),
  translate('t_and_c_heading_1'),
  translate('t_and_c_heading_2'),
  translate('t_and_c_heading_3'),
  translate('t_and_c_content_1'),
  translate('t_and_c_content_2'),
  translate('t_and_c_heading_4'),
  translate('t_and_c_content_3'),
  translate('t_and_c_content_4'),
  translate('t_and_c_heading_5'),
  translate('t_and_c_content_5'),
  translate('t_and_c_heading_6'),
  translate('t_and_c_content_6'),
  translate('t_and_c_heading_7'),
  translate('t_and_c_content_7'),
  translate('t_and_c_heading_8'),
  translate('t_and_c_content_8'),
  translate('t_and_c_heading_9'),
  translate('t_and_c_content_9'),
  translate('t_and_c_heading_10'),
  translate('t_and_c_content_10'),
  translate('t_and_c_content_11'),
  translate('t_and_c_heading_11'),
  translate('t_and_c_content_12'),
  translate('t_and_c_heading_12'),
  translate('t_and_c_content_13'),
  translate('t_and_c_content_14'),
  translate('t_and_c_content_15'),
  translate('t_and_c_content_16'),
  translate('t_and_c_heading_13'),
  translate('t_and_c_content_17'),
  translate('t_and_c_content_18'),
  translate('t_and_c_heading_14'),
  translate('t_and_c_content_19'),
  translate('t_and_c_heading_15'),
  translate('t_and_c_content_20'),
  translate('t_and_c_heading_16'),
  translate('t_and_c_content_21'),
]
